In [2]:
import fastf1

In [21]:
schedule = fastf1.get_event_schedule(2025)
schedule

,RoundNumber,Country,Location,OfficialEventName,EventDate,EventName,EventFormat,Session1,Session1Date,Session1DateUtc,...,Session3,Session3Date,Session3DateUtc,Session4,Session4Date,Session4DateUtc,Session5,Session5Date,Session5DateUtc,F1ApiSupport
0,0,Bahrain,Sakhir,FORMULA 1 ARAMCO PRE-SEASON TESTING 2025,2025-02-28,Pre-Season Testing,testing,Practice 1,2025-02-26 10:00:00+03:00,2025-02-26 07:00:00,...,Practice 3,2025-02-28 10:00:00+03:00,2025-02-28 07:00:00,None,NaT,NaT,None,NaT,NaT,True
1,1,Australia,Melbourne,FORMULA 1 LOUIS VUITTON AUSTRALIAN GRAND PRIX ...,2025-03-16,Australian Grand Prix,conventional,Practice 1,2025-03-14 12:30:00+11:00,2025-03-14 01:30:00,...,Practice 3,2025-03-15 12:30:00+11:00,2025-03-15 01:30:00,Qualifying,2025-03-15 16:00:00+11:00,2025-03-15 05:00:00,Race,2025-03-16 15:00:00+11:00,2025-03-16 04:00:00,True
2,2,China,Shanghai,FORMULA 1 HEINEKEN CHINESE GRAND PRIX 2025,2025-03-23,Chinese Grand Prix,sprint_qualifying,Practice 1,2025-03-21 11:30:00+08:00,2025-03-21 03:30:00,...,Sprint,2025-03-22 11:00:00+08:00,2025-03-22 03:00:00,Qualifying,2025-03-22 15:00:00+08:00,2025-03-22 07:00:00,Race,2025-03-23 15:00:00+08:00,2025-03-23 07:00:00,True
3,3,Japan,Suzuka,FORMULA 1 LENOVO JAPANESE GRAND PRIX 2025,2025-04-06,Japanese Grand Prix,conventional,Practice 1,2025-04-04 11:30:00+09:00,2025-04-04 02:30:00,...,Practice 3,2025-04-05 11:30:00+09:00,2025-04-05 02:30:00,Qualifying,2025-04-05 15:00:00+09:00,2025-04-05 06:00:00,Race,2025-04-06 14:00:00+09:00,2025-04-06 05:00:00,True
4,4,Bahrain,Sakhir,FORMULA 1 GULF AIR BAHRAIN GRAND PRIX 2025,2025-04-13,Bahrain Grand Prix,conventional,Practice 1,2025-04-11 14:30:00+03:00,2025-04-11 11:30:00,...,Practice 3,2025-04-12 15:30:00+03:00,2025-04-12 12:30:00,Qualifying,2025-04-12 19:00:00+03:00,2025-04-12 16:00:00,Race,2025-04-13 18:00:00+03:00,2025-04-13 15:00:00,True
5,5,Saudi Arabia,Jeddah,FORMULA 1 STC SAUDI ARABIAN GRAND PRIX 2025,2025-04-20,Saudi Arabian Grand Prix,conventional,Practice 1,2025-04-18 16:30:00+03:00,2025-04-18 13:30:00,...,Practice 3,2025-04-19 16:30:00+03:00,2025-04-19 13:30:00,Qualifying,2025-04-19 20:00:00+03:00,2025-04-19 17:00:00,Race,2025-04-20 20:00:00+03:00,2025-04-20 17:00:00,True
6,6,United States,Miami,FORMULA 1 CRYPTO.COM MIAMI GRAND PRIX 2025,2025-05-04,Miami Grand Prix,sprint_qualifying,Practice 1,2025-05-02 12:30:00-04:00,2025-05-02 16:30:00,...,Sprint,2025-05-03 12:00:00-04:00,2025-05-03 16:00:00,Qualifying,2025-05-03 16:00:00-04:00,2025-05-03 20:00:00,Race,2025-05-04 16:00:00-04:00,2025-05-04 20:00:00,True
7,7,Italy,Imola,FORMULA 1 AWS GRAN PREMIO DEL MADE IN ITALY E ...,2025-05-18,Emilia Romagna Grand Prix,conventional,Practice 1,2025-05-16 13:30:00+02:00,2025-05-16 11:30:00,...,Practice 3,2025-05-17 12:30:00+02:00,2025-05-17 10:30:00,Qualifying,2025-05-17 16:00:00+02:00,2025-05-17 14:00:00,Race,2025-05-18 15:00:00+02:00,2025-05-18 13:00:00,True
8,8,Monaco,Monaco,FORMULA 1 TAG HEUER GRAND PRIX DE MONACO 2025,2025-05-25,Monaco Grand Prix,conventional,Practice 1,2025-05-23 13:30:00+02:00,2025-05-23 11:30:00,...,Practice 3,2025-05-24 12:30:00+02:00,2025-05-24 10:30:00,Qualifying,2025-05-24 16:00:00+02:00,2025-05-24 14:00:00,Race,2025-05-25 15:00:00+02:00,2025-05-25 13:00:00,True
9,9,Spain,Barcelona,FORMULA 1 ARAMCO GRAN PREMIO DE ESPAÑA 2025,2025-06-01,Spanish Grand Prix,conventional,Practice 1,2025-05-30 13:30:00+02:00,2025-05-30 11:30:00,...,Practice 3,2025-05-31 12:30:00+02:00,2025-05-31 10:30:00,Qualifying,2025-05-31 16:00:00+02:00,2025-05-31 14:00:00,Race,2025-06-01 15:00:00+02:00,2025-06-01 13:00:00,True
10,10,Canada,Montréal,FORMULA 1 PIRELLI GRAND PRIX DU CANADA 2025,2025-06-15,Canadian Grand Prix,conventional,Practice 1,2025-06-13 13:30:00-04:00,2025-06-13 17:30:00,...,Practice 3,2025-06-14 12:30:00-04:00,2025-06-14 16:30:00,Qualifying,2025-06-14 16:00:00-04:00,2025-06-14 20:00:00,Race,2025-06-15 14:00:00-04:00,2025-06-15 18:00:00,True
11,11,Austria,Spielberg,FORMULA 1 MSC CRUISES AUSTRIAN GRAND PRIX 2025,2025-06-29,Austrian Grand Prix,conventional,Practice 1,2025-06-27 13:30:00+02:00,2025-06-27 11:30:00,...,Practice 3,2025-06-28 12:30:00+02:00,2025-06-28 10:30:00,Qualifying,2025-06-28 16:00:00+02:00,2025-06-28 14:00:00,Race,2025-06-29 15:00:00+02:00,2025-06-29 13:00:00,True
12,12,United Kingdom,Silverstone,FORMULA 1 QATAR AIRWAYS BRITISH GRAND PRIX 2025,2025-07-06,British Grand Prix,conventional,Practice 1,2025-07-04 12:30:00+01:00,2025-07-04 11:30:00,...,Practice 3,2025-07-05 11:30:00+01:00,2025-07-05 10:30:00,Qualifying,2025-07-05 15:00:00+01:00,2025-07-05 14:00:00,Race,2025-07-06 15:00:00+01:00,2025-07-06 14:00:00,True
13,13,Belgium,Spa-Francorchamps,FORMULA 1 MOËT & CHANDON BELGIAN GRAND PRIX 2025,2025-07-27,Belgian Grand Prix,sprint_qualifying,Practice 1,2025-07-25 12:30:00+02:00,2025-07-25 10:30:00,...,Sprint,2025-07-26 12:00:00+02:00,2025-07-26 10:00:00,Qualifying,2025-07-26 16:00:00+02:00,2025-07-26 14:00:00,Race,2025-07-27 15:00:00+02:00,2025-07-27 13:00:00,True
14,14,Hungary,Budapest,FORMULA 1 LENOVO HUNGARIAN GRAND PRIX 2025,2025-08-03,Hungarian Grand Prix,conventional,Practice 1,2025-08-01 13:30:00+02:00,2025-08-01 11:30:00,...,Practice 3,2025-08-02 12:30:00+02:00,2025-08-02 10:30:00,Qualifying,2025-08-02 16:00:00+02:00,2025-08-02 14:00:00,Race,2025-08-03 15:00:00+02:00,2025-08-03 13:00:00,True
15,15,Netherlands,Zandvoort,FORMULA 1 HEINEKEN DUTCH GRAND PRIX 2025,2025-08-31,Dutch Grand Prix,conventional,Practice 1,2025-08-29 12:30:00+02:00,2025-08-29 10:30:00,...,Practice 3,2025-08-30 11:30:00+02:00,2025-08-30 09:30:00,Qualifying,2025-08-30 15:00:00+02:00,2025-08-30 13:00:00,Race,2025-08-31 15:00:00+02:00,2025-08-31 13:00:00,True
16,16,Italy,Monza,FORMULA 1 PIRELLI GRAN PREMIO D’ITALIA 2025,2025-09-07,Italian Grand Prix,conventional,Practice 1,2025-09-05 13:30:00+02:00,2025-09-05 11:30:00,...,Practice 3,2025-09-06 12:30:00+02:00,2025-09-06 10:30:00,Qualifying,2025-09-06 16:00:00+02:00,2025-09-06 14:00:00,Race,2025-09-07 15:00:00+02:00,2025-09-07 13:00:00,True
17,17,Azerbaijan,Baku,FORMULA 1 QATAR AIRWAYS AZERBAIJAN GRAND PRIX ...,2025-09-21,Azerbaijan Grand Prix,conventional,Practice 1,2025-09-19 12:30:00+04:00,2025-09-19 08:30:00,...,Practice 3,2025-09-20 12:30:00+04:00,2025-09-20 08:30:00,Qualifying,2025-09-20 16:00:00+04:00,2025-09-20 12:00:00,Race,2025-09-21 15:00:00+04:00,2025-09-21 11:00:00,True
18,18,Singapore,Marina Bay,FORMULA 1 SINGAPORE AIRLINES SINGAPORE GRAND P...,2025-10-05,Singapore Grand Prix,conventional,Practice 1,2025-10-03 17:30:00+08:00,2025-10-03 09:30:00,...,Practice 3,2025-10-04 17:30:00+08:00,2025-10-04 09:30:00,Qualifying,2025-10-04 21:00:00+08:00,2025-10-04 13:00:00,Race,2025-10-05 20:00:00+08:00,2025-10-05 12:00:00,True
19,19,United States,Austin,FORMULA 1 MSC CRUISES UNITED STATES GRAND PRIX...,2025-10-19,United States Grand Prix,sprint_qualifying,Practice 1,2025-10-17 12:30:00-05:00,2025-10-17 17:30:00,...,Sprint,2025-10-18 12:00:00-05:00,2025-10-18 17:00:00,Qualifying,2025-10-18 16:00:00-05:00,2025-10-18 21:00:00,Race,2025-10-19 14:00:00-05:00,2025-10-19 19:00:00,True
20,20,Mexico,Mexico City,FORMULA 1 GRAN PREMIO DE LA CIUDAD DE MÉXICO 2025,2025-10-26,Mexico City Grand Prix,conventional,Practice 1,2025-10-24 12:30:00-06:00,2025-10-24 18:30:00,...,Practice 3,2025-10-25 11:30:00-06:00,2025-10-25 17:30:00,Qualifying,2025-10-25 15:00:00-06:00,2025-10-25 21:00:00,Race,2025-10-26 14:00:00-06:00,2025-10-26 20:00:00,True
21,21,Brazil,São Paulo,FORMULA 1 MSC CRUISES GRANDE PRÊMIO DE SÃO PAU...,2025-11-09,São Paulo Grand Prix,sprint_qualifying,Practice 1,2025-11-07 11:30:00-03:00,2025-11-07 14:30:00,...,Sprint,2025-11-08 11:00:00-03:00,2025-11-08 14:00:00,Qualifying,2025-11-08 15:00:00-03:00,2025-11-08 18:00:00,Race,2025-11-09 14:00:00-03:00,2025-11-09 17:00:00,True
22,22,United States,Las Vegas,FORMULA 1 HEINEKEN LAS VEGAS GRAND PRIX 2025,2025-11-22,Las Vegas Grand Prix,conventional,Practice 1,2025-11-20 16:30:00-08:00,2025-11-21 00:30:00,...,Practice 3,2025-11-21 16:30:00-08:00,2025-11-22 00:30:00,Qualifying,2025-11-21 20:00:00-08:00,2025-11-22 04:00:00,Race,2025-11-22 20:00:00-08:00,2025-11-23 04:00:00,True
23,23,Qatar,Lusail,FORMULA 1 QATAR AIRWAYS QATAR GRAND PRIX 2025,2025-11-30,Qatar Grand Prix,sprint_qualifying,Practice 1,2025-11-28 16:30:00+03:00,2025-11-28 13:30:00,...,Sprint,2025-11-29 17:00:00+03:00,2025-11-29 14:00:00,Qualifying,2025-11-29 21:00:00+03:00,2025-11-29 18:00:00,Race,2025-11-30 19:00:00+03:00,2025-11-30 16:00:00,True
24,24,United Arab Emirates,Yas Island,FORMULA 1 ETIHAD AIRWAYS ABU DHABI GRAND PRIX ...,2025-12-07,Abu Dhabi Grand Prix,conventional,Practice 1,2025-12-05 13:30:00+04:00,2025-12-05 09:30:00,...,Practice 3,2025-12-06 14:30:00+04:00,2025-12-06 10:30:00,Qualifying,2025-12-06 18:00:00+04:00,2025-12-06 14:00:00,Race,2025-12-07 17:00:00+04:00,2025-12-07 13:00:00,True

In [22]:
gp_Country_2024 = schedule['Country'].tail(24)
gp_Country_2024

1                Australia
2                    China
3                    Japan
4                  Bahrain
5             Saudi Arabia
6            United States
7                    Italy
8                   Monaco
9                    Spain
10                  Canada
11                 Austria
12          United Kingdom
13                 Belgium
14                 Hungary
15             Netherlands
16                   Italy
17              Azerbaijan
18               Singapore
19           United States
20                  Mexico
21                  Brazil
22           United States
23                   Qatar
24    United Arab Emirates
Name: Country, dtype: object

In [18]:
session = fastf1.get_session(2024, 'Miami', 'R')
session.load()

core           INFO 	Loading data for Miami Grand Prix - Race [v3.5.3]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for session_status_data. Loading data...
_api           INFO 	Fetching session status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for lap_count. Loading data...
_api           INFO 	Fetching lap count data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for track_status_data. Loading data...
_api           INFO 	Fetching track status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for _extended_timing_data. Loading data...
_api           INFO 	Fetching timing data...
_api           INFO 	Parsing timing data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for timing_app_data. Loading data...
_api           INFO 	Fetching timing app data...
req            INFO 	Data has been written to cache!
core           INFO 	Processing timing data...
req            INFO 	No cached data found for car_data. Loading data...
_api           INFO 	Fetching car data...
_api           INFO 	Parsing car data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for position_data. Loading data...
_api           INFO 	Fetching position data...
_api           INFO 	Parsing position data...
_api        WARNING 	Driver 241: Position data is incomplete!
_api        WARNING 	Driver 242: Position data is incomplete!
_api        WARNING 	Driver 243: Position data is incomplete!
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for weather_data. Loading data...
_api           INFO 	Fetching weather data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for race_control_messages. Loading data...
_api           INFO 	Fetching race control messages...
req            INFO 	Data has been written to cache!
core           INFO 	Finished loading data for 20 drivers: ['4', '1', '16', '11', '55', '44', '22', '63', '14', '31', '27', '10', '81', '24', '3', '77', '18', '23', '20', '2']

In [19]:
results = session.results
#results['Race'] = 'Australia'
#results['Year'] = 2024
results

,DriverNumber,BroadcastName,Abbreviation,DriverId,TeamName,TeamColor,TeamId,FirstName,LastName,FullName,...,CountryCode,Position,ClassifiedPosition,GridPosition,Q1,Q2,Q3,Time,Status,Points
4,4,L NORRIS,NOR,norris,McLaren,FF8000,mclaren,Lando,Norris,Lando Norris,...,GBR,1.0,1,5.0,NaT,NaT,NaT,0 days 01:30:49.876000,Finished,25.0
1,1,M VERSTAPPEN,VER,max_verstappen,Red Bull Racing,3671C6,red_bull,Max,Verstappen,Max Verstappen,...,NED,2.0,2,1.0,NaT,NaT,NaT,0 days 00:00:07.612000,Finished,18.0
16,16,C LECLERC,LEC,leclerc,Ferrari,E80020,ferrari,Charles,Leclerc,Charles Leclerc,...,MON,3.0,3,2.0,NaT,NaT,NaT,0 days 00:00:09.920000,Finished,15.0
11,11,S PEREZ,PER,perez,Red Bull Racing,3671C6,red_bull,Sergio,Perez,Sergio Perez,...,MEX,4.0,4,4.0,NaT,NaT,NaT,0 days 00:00:14.650000,Finished,12.0
55,55,C SAINZ,SAI,sainz,Ferrari,E80020,ferrari,Carlos,Sainz,Carlos Sainz,...,ESP,5.0,5,3.0,NaT,NaT,NaT,0 days 00:00:16.407000,Finished,10.0
44,44,L HAMILTON,HAM,hamilton,Mercedes,27F4D2,mercedes,Lewis,Hamilton,Lewis Hamilton,...,GBR,6.0,6,8.0,NaT,NaT,NaT,0 days 00:00:16.585000,Finished,8.0
22,22,Y TSUNODA,TSU,tsunoda,RB,6692FF,rb,Yuki,Tsunoda,Yuki Tsunoda,...,JPN,7.0,7,10.0,NaT,NaT,NaT,0 days 00:00:26.185000,Finished,6.0
63,63,G RUSSELL,RUS,russell,Mercedes,27F4D2,mercedes,George,Russell,George Russell,...,GBR,8.0,8,7.0,NaT,NaT,NaT,0 days 00:00:34.789000,Finished,4.0
14,14,F ALONSO,ALO,alonso,Aston Martin,229971,aston_martin,Fernando,Alonso,Fernando Alonso,...,ESP,9.0,9,15.0,NaT,NaT,NaT,0 days 00:00:37.107000,Finished,2.0
31,31,E OCON,OCO,ocon,Alpine,0093cc,alpine,Esteban,Ocon,Esteban Ocon,...,FRA,10.0,10,13.0,NaT,NaT,NaT,0 days 00:00:39.746000,Finished,1.0
27,27,N HULKENBERG,HUL,hulkenberg,Haas F1 Team,B6BABD,haas,Nico,Hulkenberg,Nico Hulkenberg,...,GER,11.0,11,9.0,NaT,NaT,NaT,0 days 00:00:40.789000,Finished,0.0
10,10,P GASLY,GAS,gasly,Alpine,0093cc,alpine,Pierre,Gasly,Pierre Gasly,...,FRA,12.0,12,12.0,NaT,NaT,NaT,0 days 00:00:44.958000,Finished,0.0
81,81,O PIASTRI,PIA,piastri,McLaren,FF8000,mclaren,Oscar,Piastri,Oscar Piastri,...,AUS,13.0,13,6.0,NaT,NaT,NaT,0 days 00:00:49.756000,Finished,0.0
24,24,G ZHOU,ZHO,zhou,Kick Sauber,52e252,sauber,Guanyu,Zhou,Guanyu Zhou,...,CHN,14.0,14,19.0,NaT,NaT,NaT,0 days 00:00:49.979000,Finished,0.0
3,3,D RICCIARDO,RIC,ricciardo,RB,6692FF,rb,Daniel,Ricciardo,Daniel Ricciardo,...,AUS,15.0,15,20.0,NaT,NaT,NaT,0 days 00:00:50.956000,Finished,0.0
77,77,V BOTTAS,BOT,bottas,Kick Sauber,52e252,sauber,Valtteri,Bottas,Valtteri Bottas,...,FIN,16.0,16,16.0,NaT,NaT,NaT,0 days 00:00:52.356000,Finished,0.0
18,18,L STROLL,STR,stroll,Aston Martin,229971,aston_martin,Lance,Stroll,Lance Stroll,...,CAN,17.0,17,11.0,NaT,NaT,NaT,0 days 00:00:55.173000,Finished,0.0
23,23,A ALBON,ALB,albon,Williams,64C4FF,williams,Alexander,Albon,Alexander Albon,...,THA,18.0,18,14.0,NaT,NaT,NaT,0 days 00:01:16.091000,Finished,0.0
20,20,K MAGNUSSEN,MAG,kevin_magnussen,Haas F1 Team,B6BABD,haas,Kevin,Magnussen,Kevin Magnussen,...,DEN,19.0,19,18.0,NaT,NaT,NaT,0 days 00:01:24.683000,Finished,0.0
2,2,L SARGEANT,SAR,sargeant,Williams,64C4FF,williams,Logan,Sargeant,Logan Sargeant,...,USA,20.0,R,17.0,NaT,NaT,NaT,NaT,Retired,0.0